0.3/2014-06-12--ru_country_name.xml: fix migration on MySQL database.
Remove workaround that isn't required anymore because it was fixed after Liquibase update.

Fix the following exception:
MySQLSyntaxErrorException: You have an error in your SQL syntax; check the
manual that corresponds to your MySQL server version for the right syntax to
use near 'NULL' at line 1

Correction for 7434210c5fd10af188a0b01b98c172c219283c57 commit.