fix(0.4/2017-05-29--test_image.xml): use type-aware attribute to fix migration on PostgreSQL.
The failure was:
MigrationFailedException: Migration failed for change set classpath:/liquibase/version/0.4/2017-05-29--test_image.xml::add-test-image::php-coder:
Reason: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException:
ERROR: column "image_id" is of type integer but expression is of type character varying
Hint: You will need to rewrite or cast the expression.

Addressed to #1034