build(pom.xml): update wiremock-maven-plugin to 5.0.0
Also updates WireMock to 2.25.1

I hope that this update also fixes #1131

Number of threads was increased in order to fix

java.lang.RuntimeException: java.lang.IllegalStateException: Insufficient configured threads:
required=4 < max=4 for
QueuedThreadPool[qtp1370494288]@51b01550{STARTED,4<=4<=4,i=4,r=1,q=0}[ReservedThreadExecutor@748f93bb{s=0/1,p=0}]

that started to appear after switching from wiremock to wiremock-jre8

Changelogs:
- https://github.com/automatictester/wiremock-maven-plugin/releases/tag/4.5.0
- https://github.com/automatictester/wiremock-maven-plugin/releases/tag/4.6.0
- https://github.com/automatictester/wiremock-maven-plugin/releases/tag/5.0.0
- https://github.com/automatictester/wiremock-maven-plugin#whats-new-in-version-500-and-above
- 2.24.0: https://groups.google.com/forum/#!topic/wiremock-user/1aUkOVdmudY
- 2.24.1: https://groups.google.com/forum/#!topic/wiremock-user/PaT8DmG9GiM
- 2.25.0: https://groups.google.com/forum/#!topic/wiremock-user/bxG2-yb-u-Y
- 2.25.1: https://groups.google.com/forum/#!topic/wiremock-user/DQcYpWieB5c