fix(0.4/2016-*-*--unique_slug_in_*.xml): don't use alias in a HAVING clause to fix precondition on PostgreSQL.
The failures were like the following:
MigrationFailedException: Migration failed for change set classpath:/liquibase/version/0.4/2016-01-14--unique_slug_in_countries.xml::add-unique-constraint-to-slug-in-countries-table::AleksSPb:
Reason:
classpath:/liquibase/changelog.xml : liquibase.precondition.core.SqlPrecondition@74bdc168 : ERROR: column "num" does not exist
Position: 72
...
Caused by: liquibase.exception.DatabaseException: Error executing SQL SELECT COUNT(*) as num FROM countries GROUP BY slug HAVING num > 1 UNION SELECT 0:
ERROR: column "num" does not exist

Addressed to #1034