chore(0.4.2/2019-11-27--add_collections_series_id.xml): fix migration on MySQL.
The error was:
liquibase.exception.ValidationFailedException: Validation Failed:
  1 changes have validation failures
    Cannot add a non-primary key identity column, classpath:/liquibase/version/0.4.2/2019-11-27--add_collections_series_id.xml::add-collections_series-id-field::php-coder

Use a single <addColumn> statement for MySQL/PostgreSQL and perform it in the 2 steps for H2.
Also remove beforeColumn that didn't work -- MySQL doesn't support it so we use FIRST clause
instead. PostgreSQL doesn't support defining a column position at all. For H2 use FIRST as well.

Correction for 2675e9f4652e09b51d42e83f2f0e8802e4a035ce commit.

Address to #1123