pom.xml: downgrade Selenium to 2.45.0
Selenium 2.46.0 requires htmlunit 2.17 and httpclient 4.5 but htmlunit doesn't work well with
httpclient 4.5. So, I downgraded Selenium to use previous release that depends on older htmlunit.

Fix the following exception during integration tests:
NoClassDefFoundError: org/apache/http/conn/ssl/NoopHostnameVerifier