0.3/2014-08-30--collections.xml: fix migration on MySQL database.
I've just change case of the table name from COLLECTIONS to collections.

Fix the following exception:
MySQLSyntaxErrorException: Table 'mystamps.COLLECTIONS' doesn't exist

Correction for 227b9a5d861dc79a391d92882576f24aa0d76179 commit.