pom.xml: updated Hibernate to 4.3.6.Final
@see http://in.relation.to/Bloggers/HibernateORM420CR1Released
@see http://in.relation.to/Bloggers/HibernateORM420CR2Released
@see http://in.relation.to/Bloggers/HibernateORM420FinalAnd4111FinalReleased
@see http://in.relation.to/Bloggers/HibernateORM430CR1Release
@see http://in.relation.to/Bloggers/HibernateORM430CR2Release
@see http://in.relation.to/Bloggers/HibernateORM430FinalRelease
@see http://in.relation.to/Bloggers/HibernateORM431FinalRelease
@see http://in.relation.to/Bloggers/HibernateORM432FinalReleased
@see http://in.relation.to/Bloggers/HibernateORM434Final4210FinalReleased
@see http://in.relation.to/Bloggers/HibernateORM435FinalReleased
@see http://in.relation.to/Bloggers/HibernateORM436FinalAnd4215FinalReleased

I also explicitly added xml-apis:xml-apis dependency because without it integration tests wails with
java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal

@see http://stackoverflow.com/questions/17777821/maven-dependency-conflict-org-w3c-dom-elementtraversal
@see http://stackoverflow.com/questions/10234201/appengine-error-java-lang-noclassdeffounderror-org-w3c-dom-elementtraversal

No functional changes.