fix: change commands order to fix installation of html5validator and rflint.
It seems like old version of ansible pulled some old dependency that
affects pip:

File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
  import OpenSSL.SSL
File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
  from OpenSSL import rand, crypto, SSL
File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
  SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

When we install html5validator/rflint first we don't have that issue
because one of them pulled a newer version of a dependency that is
needed by pip.

Fix #1020