fix(0.4/2015-06-22--image_url.xml): explicitly cast a string to an integer on PostgreSQL.
The failure was:
liquibase.exception.DatabaseException: ERROR: column "image_id" is of type integer but expression is of type text
Hint: You will need to rewrite or cast the expression.
Position: 75 [Failed SQL: INSERT INTO series_images(series_id, image_id) SELECT id AS series_id, REPLACE(image_url, '/image/', '') AS image_id FROM series]

Addressed to #1034