revert: "build(pom.xml): update H2 to 1.4.199"
H2 starting from 1.4.198 is broken and fails with error:

liquibase.exception.MigrationFailedException: Migration failed for change set classpath:/liquibase/version/0.4/2017-11-14--separate_buyers_and_sellers.xml::make-is_buyer-non-nullable::php-coder:
     Reason:
          classpath:/liquibase/changelog.xml : SQL Precondition failed.  Expected '0' got '3'

This reverts commit f087be3596f32d06e1007f1a20d5e20aa4e09b99.