chore: fix build by including hamcrest-core into "test" scope.
Otherwise tests are failing:
[ERROR] initializationError(ru.mystamps.web.feature.country.JdbcCountryDaoTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing

Correction for 91cf6639268a65d1b024ccd5958394637e3c114a commit.