revert: "build: use a lightweight API dependency"
This reverts commit 79331185a536b10d689ada32f163aa22cffb7ecf.

It has turned out that it causes an exception:
java.lang.NoClassDefFoundError: com/sun/mail/util/PropUtil

Fix #1601