fix: the queries for adding catalog numbers were failing on PostgreSQL.
The error was:
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [INSERT
INTO michel_catalog(code) SELECT ? AS code FROM dual WHERE NOT EXISTS( SELECT * FROM michel_catalog
WHERE code = ? )]; nested exception is org.postgresql.util.PSQLException: ERROR: relation
"dual" does not exist

It's not clear why these queries didn't work without "FROM dual" before as I see that they work now.

This commit reverts changes from b2eb7d097c2f7e859fb480b963e1191638dc1db7

The last part that finally fixes #1140