build: add a workaround for minify-maven-plugin to make it work with Maven 3.9+
minify-maven-plugin has started to fail on Maven 3.9:

Error:  Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.6:minify (minify-resources)
on project mystamps: Execution minify-resources of goal
com.samaxes.maven:minify-maven-plugin:1.7.6:minify failed: A required class was missing while
executing com.samaxes.maven:minify-maven-plugin:1.7.6:minify: org/codehaus/plexus/util/DirectoryScanner

Because newer Maven versions doesn't provide plexus-utils anymore.

Fix #1734