test-series-with-catalogs-numbers.sql: use a proper value for representing boolean.
This makes possible to load test data into PostgreSQL. Prior this change
the process was failing with the following error:

ERROR: column "perforated" is of type boolean but expression is of type integer
Hint: You will need to rewrite or cast the expression.

Position: 120 [Failed SQL: INSERT INTO series(id, quantity, perforated,
image_url, created_at, created_by, updated_at, updated_by) VALUES (1, 1,
1, '/image/1', NOW(), 4, NOW(), 4)]