Revert "pom.xml: updated Hibernate to 4.0.0.Final"
This reverts commit 56c8bc377f75d9dfeaf41e219e47fa4e7707bbff.

Reverted because it breaks `mvn -P test hibernate3:hbm2ddl`:

[ERROR] Failed to execute goal org.codehaus.mojo:hibernate3-maven-plugin:2.2:hbm2ddl (default-cli)
on project mystamps: Execution default-cli of goal org.codehaus.mojo:hibernate3-maven-plugin:2.2:hbm2ddl
failed: An API incompatibility was encountered while executing
org.codehaus.mojo:hibernate3-maven-plugin:2.2:hbm2ddl: java.lang.NoSuchMethodError:
org.hibernate.ejb.Ejb3Configuration.getHibernateConfiguration()Lorg/hibernate/cfg/AnnotationConfiguration;