ci: pin ruamel.yaml.clib instead of ruamel.yaml
ruamel.yaml doesn't have 0.2.2 version:
ERROR: Could not find a version that satisfies the requirement ruamel.yaml==0.2.2

Correction for 8447ddb2f4944906a97619c9964afff3e2ff7842 commit.

Fix #1536